/*run this to see properties of columns*/

SELECT 
    TABLE_SCHEMA AS [Schema],
    TABLE_NAME AS [Table],
    COLUMN_NAME AS [Column],
    ORDINAL_POSITION AS [Position],
    COLUMN_DEFAULT AS [Default],
    IS_NULLABLE AS [Nullable],
    DATA_TYPE AS [DataType],
    CHARACTER_MAXIMUM_LENGTH AS [MaxLength],
    NUMERIC_PRECISION AS [NumericPrecision],
    NUMERIC_SCALE AS [NumericScale],
    COLUMNPROPERTY(OBJECT_ID(TABLE_NAME), COLUMN_NAME, 'IsIdentity') AS [IsIdentity],
    COLUMNPROPERTY(OBJECT_ID(TABLE_NAME), COLUMN_NAME, 'IsComputed') AS [IsComputed]
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'User'
ORDER BY ORDINAL_POSITION;
SELECT * FROM [USER] 

SELECT 
    TABLE_SCHEMA AS [Schema],
    TABLE_NAME AS [Table],
    COLUMN_NAME AS [Column],
    ORDINAL_POSITION AS [Position],
    COLUMN_DEFAULT AS [Default],
    IS_NULLABLE AS [Nullable],
    DATA_TYPE AS [DataType],
    CHARACTER_MAXIMUM_LENGTH AS [MaxLength],
    NUMERIC_PRECISION AS [NumericPrecision],
    NUMERIC_SCALE AS [NumericScale],
    COLUMNPROPERTY(OBJECT_ID(TABLE_NAME), COLUMN_NAME, 'IsIdentity') AS [IsIdentity],
    COLUMNPROPERTY(OBJECT_ID(TABLE_NAME), COLUMN_NAME, 'IsComputed') AS [IsComputed]
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Messages'
ORDER BY ORDINAL_POSITION;
SELECT * FROM [MESSAGES]
